### ISSUE TITLE
dict-like access doesn't work anymore

### ISSUE THREAD

**Issue by jpaniagualaconich** [fattureincloud/fattureincloud-python-sdk#63]
**Describe the bug**
After upgrading to 2.0.12 or newer, accessing objects using dict notation does not work anymore.

**Env info**
- python version: 3.11.2
- fattureincloud-python-sdk in {'2.0.12', '2.0.13', '2.0.14', '2.0.15'} (it was working fine until '2.0.11')

**To Reproduce**

```python
from fattureincloud_python_sdk import ApiClient, ApiException, Configuration
from fattureincloud_python_sdk.api.issued_documents_api import IssuedDocumentsApi

company_id = 111222
access_token = "my-secret-token"
invoice_number = 666
invoice_numeration = "-NUMERATION"

config = Configuration()
config.access_token = access_token
api_client = ApiClient(configuration=config)
issued_documents_api = IssuedDocumentsApi(api_client)

request_kwargs = {
    "fieldset": "detailed",
    "q": f"number='{invoice_number}' AND numeration='{invoice_numeration}'",
}

response = issued_documents_api.list_issued_documents(company_id, "invoice", **request_kwargs)
doc_list = response["data"]
```

This results in:
```txt
TypeError: 'ListIssuedDocumentsResponse' object is not subscriptable
```

**Expected behavior**
2.0.12, 2.0.13, 2.0.14, 2.0.15 are patch releases. The expectation with patch releases is that [changes are backwards compatible](https://semver.org/#summary).

**Comment by emajo** [comment]
Hi @jpaniagualaconich, the 2.0.12 release was a particular release, it's true that it's not completely backwards compatible, but that is because we fixed some wrong behaviour that never had to be there in the first place, for example the objects were never inteded to be used with the dict notation and as you said in the other issue you were able to access a field that was not mapped in the class (the `locked` field), so we are sorry that the code needs to be modified but we made modifications that needed to be made to have the SDK working as we intended.

We hope you understand,
Emanuele.

**Comment by jpaniagualaconich** [comment]
Thanks for the prompt response @emajo

I understand that releasing breaking changes is often the only way. I will modify my code accordingly.

Please consider making a major (e.g., `3.0.0`) release when more breaking changes are needed in the future. In this way "compatible release" operators in dependency rules will keep working as expected.

Feel free to close this issue at your discretion.

**Comment by valmoz** [comment]
Hi @jpaniagualaconich 
I'm sorry but we decided to not follow semver, but to bind the major version of all our SDKs to the API version (in this case, the API version is v2).
Of course, we could have used at least a new minor release to make it more clear that a breaking change was introduced, we'll try to improve our release process in the future.

I'm going to close this issue now.

Thanks
Mauro
