### ISSUE TITLE
Transform arbitrary unicode characters in e-invoice XML to acceptable format to avoid XML validation errors

### ISSUE THREAD

**Issue by vmspike** [fattureincloud/fattureincloud-python-sdk#73]
**Is your feature request related to a problem? Please describe.**
When invoice fields contains hieroglyphic characters (maybe other non-latin too) e-invoice sending failed with XML validation error (HTTP 422, Unprocessable Entity) like:
```
 {"error":{"message":"Validation XML",
        "validation_result":{
            "xml_errors":[
                "Nei dati del Cessionario Committente (cliente), il campo Nome non \u00e8 nel formato valido",
                "Nei dati del Cessionario Committente (cliente), il campo Cognome non \u00e8 nel formato valido",
                "Nei dati del Cessionario Committente (cliente), il campo Comune non \u00e8 nel formato valido"
]}}}
```

**Describe the solution you'd like**
Automatically transform non-latin unicode characters (if any) in e-invoice (XML content?) to the format accepted by the remote service (SDI?).
Guess it's `\uXXXX` notation, maybe by `json.dumps(dict, ensure_ascii=True)`.

**Describe alternatives you've considered**
Maybe mangling `ei_raw` for the fields with non-latin characters.

**Comment by valmoz** [comment]
Hi @vmspike 
we suggest you perform this operation while preparing the ei_raw, instead of while during the JSON dumps. Is it possible for you?

Thanks
Mauro

**Comment by vmspike** [comment]
Hi @valmoz, thank you for reply!

It should be a way to get rid of this error on our side, and I've started to investigate it.
Will continue if you not going to approve this feature request.

Other non- e-invoice FIC parts (which I know) work with unicode just fine.
So for my mind this task looks more suitable for the SDK itself, that's why I've opened this issue,  it's just data format/encoding conversion for tightly related service (with not clear format requirements, that ascii `\u????` conversion is just my assumption).
It would decrease complexity of the code for the end user and amount of hacks, such convenience is an advantage of using SDK, so thought you may consider it to be useful for other users too.

**Comment by valmoz** [comment]
Hi @vmspike 
I think this is not a problem of the SDK itself but of the XML validation functionality on the API side.

If you want to be sure if the problem is on the SDK side or the API side you can try to obtain the generated JSON as explained [here](https://developers.fattureincloud.it/docs/sdks/python-sdk#spiral_notepad-retrieve-the-json-request-body) and try to send it with the [API Reference](https://developers.fattureincloud.it/api-reference).

Also, if you want to verify the e-invoice instead of directly sending it you can use the [Verify e-invoice XML](https://developers.fattureincloud.it/api-reference/#get-/c/-company_id-/issued_documents/-document_id-/e_invoice/xml_verify) functionality as explained [here](https://developers.fattureincloud.it/docs/guides/e-invoice-management); this functionality uses the same verification functionality without actually sending the invoice to the SDI, so it could be useful for testing.

Thanks 
Mauro
